# base Docker image that we will build on
FROM python:3.9

# set up our image by installing prerequisites; pandas in this case
RUN apt-get install wget
RUN pip install pandas sqlalchemy psycopg2

# set up the working directory inside the container
WORKDIR /app
# copy the script to the container. 1st name is source file, 2nd is destination
COPY data_ingestion.py data_ingestion.py

# define what to do first when the container runs
# in this example, we will just run the script
ENTRYPOINT [ "python", "data_ingestion.py" ]
